services:
  app:
    build: .
    image: cortana-app:latest
    container_name: cortana-app
    ports:
      - "8000:8000"
    # Odkomentuj, jeśli chcesz SSE:
    # environment:
    #   EXPERIMENTAL_ACT_STREAM: "1"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
